name = "ComoniconTargetExpr"
uuid = "d6dfd36b-42f3-4a9f-a1cb-6f1a052fed42"
authors = ["Roger-Luo <rogerluo.rl18@gmail.com> and contributors"]
version = "0.2.3"

[deps]
ComoniconOptions = "a25bc8ac-9d24-42b2-8edd-3d267ec19fc5"
ComoniconTypes = "d0eb39ce-029e-40d1-add6-e32b3165f6a3"
ExproniconLite = "55351af7-c7e9-48d6-89ff-24e801d99491"

[compat]
ComoniconOptions = "0.1"
ComoniconTypes = "0.2"
ExproniconLite = "0.6"
julia = "1.6.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
